type AudienceSlide = { title: string; subtitle: string; body: string; bibleText: string; type?: string; countdownMinutes?: number };
const escapeHtml = (text: string) => text.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);

/** Deliberately accepts only audience fields; never serialize the full slide or speaker notes. */
export function offlinePresentationHtml(title: string, slides: AudienceSlide[]) {
  const countdownSeconds = (slide: AudienceSlide) => slide.type === 'Countdown' ? Math.min(60, Math.max(1, Math.round(Number(slide.countdownMinutes) || 5))) * 60 : 0;
  const content = slides.map((slide, index) => `<section class="slide" ${index ? 'hidden' : ''} aria-label="Slide ${index + 1}" data-countdown="${countdownSeconds(slide)}"><div class="content"><p class="subtitle">${escapeHtml(slide.subtitle)}</p><h1>${escapeHtml(slide.title)}</h1><p class="body ${slide.bibleText ? 'scripture' : ''}">${escapeHtml(slide.bibleText || slide.body)}</p>${countdownSeconds(slide) ? '<p class="timer" aria-label="Countdown remaining"></p>' : ''}</div></section>`).join('\n');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#14271f;color:#fff;font-family:Arial,sans-serif}.slide{height:100dvh;padding:5vh 7vw 12vh;display:flex;align-items:center;justify-content:center}.slide[hidden]{display:none}.content{width:100%;max-width:1400px;text-align:center}h1{font-size:clamp(26px,4vw,64px);line-height:1.1;margin:0 0 4vh;overflow-wrap:anywhere}.subtitle{font-size:clamp(16px,2vw,30px);color:#efd998}.body{font-size:clamp(20px,3vw,48px);line-height:1.3;white-space:pre-wrap;overflow-wrap:anywhere}.timer{font-size:clamp(40px,8vw,100px);font-variant-numeric:tabular-nums;margin:2vh 0}.scripture{font-family:Georgia,serif}nav{position:fixed;bottom:0;left:0;right:0;display:flex;flex-wrap:wrap;justify-content:center;align-items:center;gap:8px;padding:10px;background:#14271f}button{min-height:44px;border:1px solid #8ca393;border-radius:10px;background:#203e30;color:white;padding:10px 16px;font-size:16px}button:disabled{opacity:.4}#blank{position:fixed;inset:0;background:#000;z-index:2}#blank[hidden]{display:none}#help{font-size:12px;color:#c5d5c8}body.blanked nav{visibility:hidden}
@media print{nav,#blank{display:none!important}.slide[hidden],.slide{display:flex;height:7.5in;width:13.333in;break-after:page;padding:.6in}h1{font-size:34pt}.body{font-size:24pt}@page{size:13.333in 7.5in;margin:0}}
</style></head><body>${content}<div id="blank" hidden title="Click or press B to show slides"></div><nav aria-label="Presentation controls"><button id="previous">Previous</button><span id="count" aria-live="polite"></span><button id="next">Next</button><button id="blackout">Blank screen</button><button id="fullscreen">Full screen</button><span id="help">Arrows / Space: advance · B: blank · Home / End · F: full screen</span></nav>
<script>
const slides = Array.from(document.querySelectorAll('.slide'));
const blank = document.getElementById('blank'); let current = 0, deadline = null;
function tick(){if(deadline===null)return;const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));const timer=slides[current]?.querySelector('.timer');if(timer)timer.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left===0){deadline=null;if(current<slides.length-1)show(current+1);}}
setInterval(tick,250);
function fit(){const slide=slides[current];if(!slide)return;const body=slide.querySelector('.body');body.style.fontSize='';let size=parseFloat(getComputedStyle(body).fontSize);while(slide.scrollHeight>slide.clientHeight && size>14){size-=1;body.style.fontSize=size+'px';}}
function show(index){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((slide,i)=>slide.hidden=i!==current);const duration=Number(slides[current]?.dataset.countdown)||0;deadline=duration?Date.now()+duration*1000:null;tick();document.getElementById('count').textContent=(slides.length?current+1:0)+' / '+slides.length;document.getElementById('previous').disabled=current===0;document.getElementById('next').disabled=current===slides.length-1;fit();}
function toggleBlank(){blank.hidden=!blank.hidden;document.body.classList.toggle('blanked',!blank.hidden);}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.getElementById('help').textContent='Use your browser full-screen command.';}}
document.getElementById('previous').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);document.getElementById('blackout').onclick=toggleBlank;blank.onclick=toggleBlank;document.getElementById('fullscreen').onclick=fullscreen;
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;if(['ArrowRight','ArrowDown',' ','PageDown'].includes(e.key)){e.preventDefault();show(current+1);}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();show(current-1);}else if(e.key==='Home'){e.preventDefault();show(0);}else if(e.key==='End'){e.preventDefault();show(slides.length-1);}else if(e.key.toLowerCase()==='b'){e.preventDefault();toggleBlank();}else if(e.key.toLowerCase()==='f'){e.preventDefault();fullscreen();}else if(e.key==='Escape'&&!blank.hidden){toggleBlank();}});window.addEventListener('resize',fit);show(0);
</script></body></html>`;
}
